## Colors configuration
background #20262C
foreground #ABB2BF
selection_background #ABB2BF
selection_foreground #1E2128
cursor #ABB2BF

color0 #20262C
color8 #50545B
color1 #DB86BA
color9 #EA757E
color2 #74DD91
color10 #A2CD83
color3 #E49186
color11 #EFCA84
color4 #75DBE1
color12 #6CB8F9
color5 #B4A1DB
color13 #D282E7
color6 #9EE9EA
color14 #5FC0CC
color7 #F1FCF9
color15 #B5BCC9
