#!/bin/bash

## Set GTK Themes, Icons, Cursor and Fonts

THEME='Manhattan'
ICONS='Tela'
FONT='Noto Sans 10'
CURSOR='Future'

SCHEMA='gsettings set org.gnome.desktop.interface'

apply_themes() {
  ${SCHEMA} gtk-theme "$THEME"
  ${SCHEMA} icon-theme "$ICONS"
  ${SCHEMA} cursor-theme "$CURSOR"
  ${SCHEMA} font-name "$FONT"
}

apply_themes
