# Example per-device config
# See https://wiki.hyprland.org/Configuring/Keywords/#executing for more
#device:epic mouse V1 {
#  sensitivity = -0.5
#}

# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
#  windowrule v1
windowrule = float, yad|nm-connection-editor|pavucontrol|pavucontrol-qt|feh|xarchiver

# Floating Window
windowrule = float, title:^(Calculator)$
windowrulev2 = float, class:^(rofi)$
windowrulev2 = float, class:^(viewnior)$
windowrule = float, title:^(Btrfs Assistant)$
windowrulev2 = float, class:^(Steam), title:^(Friends List)$
windowrulev2 = float, class:^(xfce4-appfinder)$
windowrulev2 = float,class:^(floating_term)$
windowrulev2 = float, class:^(AppImageLauncher)$
windowrulev2 = float, class:^(org.kde.ark)$
windowrulev2 = float,class:^(zen)$,title:^(Picture-in-Picture)$
windowrulev2 = float,class:^(LibreWolf)$,title:^(Picture-in-Picture)$
windowrulev2 = float,class:^(firefox)$,title:^(Picture-in-Picture)$
#windowrulev2 = opacity 0.9 0.9,class:^(Cursor)$


# Example windowrule v2
windowrulev2 = tile, class:^(Spotify)$

# windowrulev2 = workspace 4, class:^(Apache Directory Studio)$
# windowrulev2 = bordercolor rgb(EE4B55) rgb(880808), fullscreen:1
# windowrulev2 = bordercolor rgb(282737) rgb(1E1D2D), floating:1
# windowrulev2 = opacity 0.8 0.8, pinned:1
# windowrulev2 = workspace 10, class:^(Microsoft-edge)$
# windowrulev2 = workspace 8 silent, class^(Steam)$, title:^(Steam)$
